### PR TITLE
Remove direct filesystem access to force portal usage

### PR DESCRIPTION
**Pull request by travier**
See https://github.com/flathub/org.kde.filelight/pull/12

### CODE REVIEW

**Comment by travier** [comment]
This works but the "Scan Home folder" button now has no meaning. CC @Pointedstick

**Comment by travier** [comment]
CC @aleixpol

**Comment by travier** [comment]
Well, we can probably just hide it

**Comment by travier** [comment]
https://invent.kde.org/utilities/filelight/-/merge_requests/65

**Comment by travier** [comment]
OK, this works for me now.

**Comment by Pointedstick** [comment]
Why doesn't the `"--filesystem=home"` permission work?

**Comment by travier** [comment]
See https://github.com/flathub/org.kde.filelight/pull/12#issue-1465416982 & https://github.com/flathub/org.kde.filelight/pull/12#issuecomment-1328928330.

I can not find this documented anywhere but essentially, with `"--filesystem=home"`,  `~/.var/app` is made a tmpfs and only  the files for the current app are made available:

```
$ flatpak run --command=bash org.kde.filelight
$ findmnt ~/.var/app
TARGET             SOURCE FSTYPE OPTIONS
/home/tim/.var/app tmpfs  tmpfs  rw,nosuid,nodev,relatime,seclabel,mode=755,uid=1000,gid=1000,inode64
$ ls  ~/.var/app/
org.kde.filelight
```

For filelight, we need to access the true content on the filesystem and not a filtered view so we need to always go through the portal.

**Comment by travier** [comment]
I've filed https://github.com/flatpak/flatpak-docs/issues/380

**Comment by travier** [comment]
This is now documented at the end of https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

**Pull request merged**
